version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: pwd && ls
          name: print working dir
      - run:
          command: . ./validateAllFiles.sh
          name: Validate all CSV files from the files folder

workflows:
  main:
    jobs:
      - build-and-test
